""" remove unneeded column

Revision ID: ab2e6dc8c125
Revises: ec13d24b9ae1
Create Date: 2025-05-04 08:28:54.271862

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'ab2e6dc8c125'
down_revision = 'ec13d24b9ae1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipe', sa.Column('cookbook_id', sa.Uuid(), nullable=False))
    op.create_foreign_key(None, 'recipe', 'cookbook', ['cookbook_id'], ['id'], ondelete='CASCADE')
    op.drop_column('recipe', 'recipe_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipe', sa.Column('recipe_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'recipe', type_='foreignkey')
    op.drop_column('recipe', 'cookbook_id')
    # ### end Alembic commands ###
