"""add recipe references

Revision ID: c941dfc7136f
Revises: 7aade931d9d8
Create Date: 2025-11-28 14:02:49.683880

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'c941dfc7136f'
down_revision = '7aade931d9d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recipereference',
    sa.Column('url', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=False),
    sa.Column('author', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('recipe_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipe.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recipestep',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('recipe_id', sa.Uuid(), nullable=False),
    sa.Column('step_instructions', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=False),
    sa.Column('step_picture', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=True),
    sa.Column('order_number', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipe.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('recipe', sa.Column('cloned_from', sa.Uuid(), nullable=True))
    op.add_column('recipe', sa.Column('tags', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True))
    op.create_foreign_key(None, 'recipe', 'recipe', ['cloned_from'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'recipe', type_='foreignkey')
    op.drop_column('recipe', 'tags')
    op.drop_column('recipe', 'cloned_from')
    op.drop_table('recipestep')
    op.drop_table('recipereference')
    # ### end Alembic commands ###
